### PR TITLE
Clean up the repository sturcture

### PR DESCRIPTION
**Pull request by jkarolczak**

### CODE REVIEW

**Review by wtaisner — COMMENTED** [review]
excellent work, thanks for the PR, as for me, merge it into main

**Review by wtaisner — APPROVED** [review]
as @annprzy once again requested my expertise, I herby declare, that this PR should be merged

**Review by annprzy — COMMENTED** [review]
Everything is perfect, the bestest clean-up of all time

**Comment by konradszewczyk** [comment]
Perfectly splendid clean-up, @jkarolczak! If it was a Software Engineering course project, it would certainly warrant the bestest grade available!

**Review by konradszewczyk — COMMENTED** [review]
Perfectly splendid clean-up, @jkarolczak! If it was a Software Engineering course project, it would certainly warrant the bestest grade available!

**Pull request merged**
